I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Chapter_Four.rpy", line 287, in script
ScriptError: could not find label 'Start_chp5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Chapter_Four.rpy", line 287, in script
  File "/Users/jaredclark/Desktop/renpy-7.3.5-sdk/renpy/ast.py", line 1697, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/jaredclark/Desktop/renpy-7.3.5-sdk/renpy/script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'Start_chp5'.

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Dracula 1.0
Wed May 20 16:18:33 2020
